datasource:
  h2:
    #ONLY FOR TESTS
    jdbcUrl: jdbc:h2:file:~/databaseScriptExecutor/databaseScriptExecutor
    driverClassName: org.h2.Driver
    username: sa
    password:
    
files:
  directory:
#    root: ~/git/databaseScriptExecutor/src/main/resources/databasescripts/
    root: C:/Users/ajunior.3mpk/git/databaseScriptExecutor/src/main/resources/databasescripts
    test-scripts-h2: scripts_h2
    temp-files: scripts_h2/tmp
    

# FOR TESTS
#  jpa:
#    properties:
#      hibernate:
#        hbm2dll.auto: update